version: "3"
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=zume
      - POSTGRES_PASSWORD=cheese
      - POSTGRES_DB=zume
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
