settings:
  files:
    outputs:
      status: true
      path: ""
      name: .r.outputs.log
    logs:
      status: true
      path: ""
      name: .r.logs.log
    errors:
      status: true
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: webstore
  path: /home/jeff/Documents/go/src/github.com/sir-wiggles/arc/pkg/webstore
  commands:
    clean:
      status: false
    vet:
      status: false
    test:
      status: true
    install:
      status: false
    run:
      status: false
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
  errorOutputPattern: =========================================
